language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

install:
  - travis_retry npm install

before_script:
  - npm run lint
script:
  - npm run build
  - npm run test:ci -- --coverage --watchAll=false
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

# Re-enable for version v2.0.0
# jobs:
#   include:
#     - stage: release
#       node_js: lts/*
#       script:
#         - npm run semantic-release

notifications:
  email:
    on_success: never
    on_failure: always
