language: node_js
node_js:
  - '6'

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - '/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24'
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn install --silent
  - export DISPLAY=':99.0'

before_script: greenkeeper-lockfile-update

script:
  - yarn run $COMMAND

after_script: greenkeeper-lockfile-upload

env:
  matrix:
    - COMMAND=test
    - CXX=g++-4.8 COMMAND=electron-test
