name: Automerge 

on:
  pull_request:
    types: [labeled, synchronize]
 
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'dependencies') || github.event.label.name == 'dependencies' }}
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: "autoapproved, dependencies, !in progress"
          MERGE_METHOD: "merge"
          MERGE_RETRIES: "6"
          MERGE_REQUIRED_APPROVALS: "1"
          UPDATE_LABELS: "automerged"
          UPDATE_METHOD: "rebase"
