name: GitHub CI

on: [push, pull_request]

jobs:
  npm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # exclude:
        #   - os: windows-latest
        #     node-version: 13.x

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with npm
        run: |
          npm install
      - name: Lint code
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
      - name: Run tests
        run: |
          npm run test:ci
      # - name: Coveralls Parallel
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GH_TOKEN }}
      #     parallel: true

  yarn:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          yarn install
      - name: Lint code
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build
      - name: Run tests
        run: |
          yarn test:ci
  # coverage:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Coveralls Finished
  #       uses: coverallsapp/github-action@master
  #       with:
  #         github-token: ${{ secrets.GH_TOKEN }}
  #         parallel-finished: true
